# Generated by Django 5.2 on 2025-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Pensée')),
                ('auteur', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
