services:
  - type: web
    name: positivity-wall
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn positivity_wall.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: positivity_wall.settings
      - key: SECRET_KEY
        generateValue: true
